version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: dio-apache-project
    ports:
    - '82:80'
    volumes:
    - ./website:/usr/local/apache2/htdocs
    networks:
      - minha-rede

networks:
  minha-rede:
